fix explicted type can be replaced by <>
cuba-platform/cuba pull request #3291
Opened 2022-12-01 23:58 UTC by centralhardware

2022-12-01 23:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cuba-platform/cuba?pullRequest=3291) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cuba-platform/cuba?pullRequest=3291) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cuba-platform/cuba?pullRequest=3291) it.</sub>

2022-12-12 08:39 UTC, glebfox commented
Hi,

Thank you for you contribution. Please remove all changes from **web-toolkit** and **widgets** modules.
* **web-toolkit** - contains Java which is translated to JavaScript code, so it's better not to change it.
* **widgets** - files in the `addons` package contains code from the embedded addons, i.e. this code isn't written by us, so it must remain unchanged.

2022-12-13 21:19 UTC, centralhardware commented
fixed

2022-12-16 08:48 UTC, glebfox requested changes

2022-12-16 08:48 UTC, glebfox commented on modules/web-widgets/src/name/fraser/neil/plaintext/diff_match_patch.java
>          // Check for equality (speedup).
This file isn't ours. Please revert any changes in this file.

2022-12-16 23:14 UTC, centralhardware commented
fixed

2022-12-19 09:08 UTC, merged